/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountInput: typeof import('./../src/components/AccountInput/index.vue')['default']
    IconBiChatRightText: typeof import('~icons/bi/chat-right-text')['default']
    IconBxsConversation: typeof import('~icons/bxs/conversation')['default']
    IconDeviconFacebook: typeof import('~icons/devicon/facebook')['default']
    IconDeviconGoogle: typeof import('~icons/devicon/google')['default']
    'IconHugeicons:menuSquare': typeof import('~icons/hugeicons/menu-square')['default']
    IconMaterialSymbolsMenu: typeof import('~icons/material-symbols/menu')['default']
    'IconMdi:like': typeof import('~icons/mdi/like')['default']
    'IconStreamline:taskList': typeof import('~icons/streamline/task-list')['default']
    'IconWpf:faq': typeof import('~icons/wpf/faq')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
